apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: infra-resources
spec:
  type: url
  targets:
    - ./storage/backstage/service1/service1.yml
    - ./storage/backstage/service1/service2.yml
    - ./storage/backstage/org.yml