apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: pet-store-team
  description: The Pet Store Unit
spec:
  type: team
  profile:
    displayName: Pet Store Team
    email: infrastructure@example.com
  children: []
  members: [jdoe]