apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: pet-store-2
  title: Pet Store
  description: Service in charge of ...
  annotations:
    github.com/project-slug: inokab/backstage-test
  tags:
    - php
  links:
    - url: https://github.com/inokab/backstage-test
      title: Repository
spec:
  type: service
  owner: pet-store-team
  system: pet-store-service
  lifecycle: production
  providesApis:
    - pet-store-api2