apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: pet-store-team
  description: The Pet Store Unit
spec:
  type: business-unit
  profile:
    displayName: Pet Store Team
    email: infrastructure@example.com
    picture: https://example.com/groups/bu-infrastructure.jpeg
  children: [backstage, other]
  members: [jdoe]